package lamport;


/**
* lamport/Lamport.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lamport.idl
* Saturday, January 11, 2020 3:52:09 PM WEST
*/

public interface Lamport extends LamportOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Lamport
