package lamport;

/**
* lamport/LamportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lamport.idl
* Saturday, January 11, 2020 3:52:09 PM WEST
*/

public final class LamportHolder implements org.omg.CORBA.portable.Streamable
{
  public lamport.Lamport value = null;

  public LamportHolder ()
  {
  }

  public LamportHolder (lamport.Lamport initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lamport.LamportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lamport.LamportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lamport.LamportHelper.type ();
  }

}
