package lamport;


/**
* lamport/LamportHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lamport.idl
* Saturday, January 11, 2020 3:52:09 PM WEST
*/

abstract public class LamportHelper
{
  private static String  _id = "IDL:lamport/Lamport:1.0";

  public static void insert (org.omg.CORBA.Any a, lamport.Lamport that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static lamport.Lamport extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (lamport.LamportHelper.id (), "Lamport");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static lamport.Lamport read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LamportStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, lamport.Lamport value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static lamport.Lamport narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof lamport.Lamport)
      return (lamport.Lamport)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      lamport._LamportStub stub = new lamport._LamportStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static lamport.Lamport unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof lamport.Lamport)
      return (lamport.Lamport)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      lamport._LamportStub stub = new lamport._LamportStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
